### ISSUE TITLE
FTW replacing \xac\xed with xc2\xac\xc3\xad

### ISSUE THREAD

**Issue by spartantri** [coreruleset/ftw#16]
I have a strange FTW behavior using raw_requests. I have the test below which is supposed to send \xac\xed\x00\x05 but for some unknown reason what I see on the apache error and modsecrutiy audit logs and confirmed on tcpdump. ftw is sending  \xc2\xac\xc3\xad\x00\x05 instead of  \xac\xed\x00\x05, if I change the rx to that the modsec rule matches without any problem to this replaced string so it is not a modsec or apache issue and tcpdump confirms the finding.

Please advise how to fix this.

    - 
      test_title: 944300-0
      desc: Argument test includes java serialization magic bytes
      stages:
        - 
          stage:
            input:
              dest_addr: "127.0.0.1"
              port: 80
              raw_request: "POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 6\r\n\r\nt=\xac\xed\x00\x05\r\n\r\n"
            output:
              log_contains: "id \"944300\""

Here is the tcpdump capture of this request
	POST / HTTP/1.0
	Host: localhost
	User-Agent: ModSecurity CRS 3 Tests
	Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
	Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
	Accept-Encoding: gzip,deflate
	Accept-Language: en-us,en;q=0.5
	Content-Type: application/x-www-form-urlencoded
	Content-Length: 6
	
[hex dump excess removed]
	0x0190:  2d4c 656e 6774 683a 2036 0d0a 0d0a 743d
	0x01a0:  c2ac c3ad 0005 0d0a 0d0a
[decoded hex]
	0x0190:  -L en gt h:  6 \r\n \r\n t=
	0x01a0: Â¬ Ã­ \r\n \r\n

**Comment by csanders-git** [comment]
hmm i shall try to reproduce this... does the same issue occur with magic off?

**Comment by spartantri** [comment]
Hi @csanders-git , I used the CRS clone, I don't know if there is any magic in it or not.

I have another test with encoded_request, both have the exact same content and it works fine using b64, there are no substitutions there.

**Comment by fzipi** [comment]
From my latest tests, there is no simple way to solve this. The preferred way to do binary data in YAML is base64 encoded.

Take a look at this simple examples below, where the same data is used in encoded form and raw:

1. Transforming `raw_request` from string to bytes:
```python
#!/usr/bin/env python

import base64
import codecs

encoded_request = "UE9TVCAvIEhUVFAvMS4wDQpIb3N0OiBsb2NhbGhvc3QNClVzZXItQWdlbnQ6IE1vZFNlY3VyaXR5IENSUyAzIFRlc3RzDQpBY2NlcHQ6IHRleHQveG1sLGFwcGxpY2F0aW9uL3htbCxhcHBsaWNhdGlvbi94aHRtbCt4bWwsdGV4dC9odG1sO3E9MC45LHRleHQvcGxhaW47cT0wLjgsaW1hZ2UvcG5nLCovKjtxPTAuNQ0KQWNjZXB0LUNoYXJzZXQ6IElTTy04ODU5LTEsdXRmLTg7cT0wLjcsKjtxPTAuNw0KQWNjZXB0LUVuY29kaW5nOiBnemlwLGRlZmxhdGUNCkFjY2VwdC1MYW5ndWFnZTogZW4tdXMsZW47cT0wLjUNCkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24veC13d3ctZm9ybS11cmxlbmNvZGVkDQpDb250ZW50LUxlbmd0aDogOQ0KDQp0ZXN0PaztAAUNCg0K"

raw_request = "POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 9\r\n\r\ntest=\xac\xed\x00\x05\r\n\r\n"

raw_request = bytes(raw_request, 'utf-8')

encoded_request = base64.b64decode(encoded_request)

print(encoded_request)
print(raw_request)
```

Will give:
```
❯ python test.py
b'POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 9\r\n\r\ntest=\xac\xed\x00\x05\r\n\r\n'
b'POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 6\r\n\r\ntest=\xc2\xac\xc3\xad\x00\x05\r\n\r\n'
```

2. Using bytes directly

```python
#!/usr/bin/env python

import base64

encoded_request = "UE9TVCAvIEhUVFAvMS4wDQpIb3N0OiBsb2NhbGhvc3QNClVzZXItQWdlbnQ6IE1vZFNlY3VyaXR5IENSUyAzIFRlc3RzDQpBY2NlcHQ6IHRleHQveG1sLGFwcGxpY2F0aW9uL3htbCxhcHBsaWNhdGlvbi94aHRtbCt4bWwsdGV4dC9odG1sO3E9MC45LHRleHQvcGxhaW47cT0wLjgsaW1hZ2UvcG5nLCovKjtxPTAuNQ0KQWNjZXB0LUNoYXJzZXQ6IElTTy04ODU5LTEsdXRmLTg7cT0wLjcsKjtxPTAuNw0KQWNjZXB0LUVuY29kaW5nOiBnemlwLGRlZmxhdGUNCkFjY2VwdC1MYW5ndWFnZTogZW4tdXMsZW47cT0wLjUNCkNvbnRlbnQtVHlwZTogYXBwbGljYXRpb24veC13d3ctZm9ybS11cmxlbmNvZGVkDQpDb250ZW50LUxlbmd0aDogOQ0KDQp0ZXN0PaztAAUNCg0K"

raw_request = b'POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 9\r\n\r\ntest=\xac\xed\x00\x05\r\n\r\n'

encoded_request = base64.b64decode(encoded_request)

print(encoded_request)
print(raw_request)
```

Will give
```
❯ python test1.py
b'POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 9\r\n\r\ntest=\xac\xed\x00\x05\r\n\r\n'
b'POST / HTTP/1.0\r\nHost: localhost\r\nUser-Agent: ModSecurity CRS 3 Tests\r\nAccept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us,en;q=0.5\r\nContent-Type: application/x-www-form-urlencoded\r\nContent-Length: 6\r\n\r\ntest=\xac\xed\x00\x05\r\n\r\n'
```

So the only one that "works" is using raw bytes as they come (this is python3). In the end, is what you are going to send over the wire, but I would say that if both do the same, we should deprecate the `raw_request` in favor of `encoded_request`.

**Comment by fzipi** [comment]
So, to close this one, and for future reference, for any complex thing you want to do **use encoded_request**
