### ISSUE TITLE
Remove noise when tests fail

### ISSUE THREAD

**Issue by spartantri** [coreruleset/ftw#17]
Would it be possible to change the default behavior of FTW when a test fail to be as short as when all tests succeed? This is especially true if sending a few hundred of rules with several tens of failures. 
Maybe have a production run mode with short meaningful output to ease scripting and error reporting.

For example, it will be fine to have some error output of why every test failed if the user ran the tests in verbose mode.
```
(env) $> py.test -sv CRS_Tests.py --ruledir=tests/REQUEST-941-APPLICATION-ATTACK-XSS
...SNIP...
CRS_Tests.py::test_crs[ruleset0-941320.yaml -- 941320-1] PASSED
CRS_Tests.py::test_crs[ruleset1-941150.yaml -- 941150-1] FAIL
=======
short summary blah blah test 941150-1 failed because of X
```

Current behavior would be good if the user ran the tests in very verbose mode
```
(env) $> py.test -svv CRS_Tests.py --ruledir=tests/REQUEST-941-APPLICATION-ATTACK-XSS
...SNIP...
CRS_Tests.py::test_crs[ruleset0-941320.yaml -- 941320-1] PASSED
CRS_Tests.py::test_crs[ruleset1-941150.yaml -- 941150-1] FAIL
=======
blah blah lots of blah blabh test 941150-1 failed because of X including python code blah blah
```

When the user runs the tests in non-verbose/normal mode a small summary would be better
```
(env) $> py.test CRS_Tests.py --ruledir=tests/REQUEST-941-APPLICATION-ATTACK-XSS
................................F...........F........FFFF........
=======
PASSED 60 rules
FAIL 6 rules
Failed rules: 1325, 2243, 3234, 4335, 5434, 6435 - No blah blah python dumps
```

**Comment by dune73** [comment]
I second this idea. It would be a welcome feature. Not essential, though. Just more convenient.

**Comment by fgsch** [comment]
This is a py.test thing. Just add `--tb=no` and should do what you want.

**Comment by spartantri** [comment]
Thanks!
