### ISSUE TITLE
FTW Containerize

### ISSUE THREAD

**Issue by zmallen** [coreruleset/ftw#2]
As a security engineer,
I would like to run ftw in a container,
so I can integrate the container into my own development pipeline

Acceptance Criteria:
	- Build a docker container to install ftw
	- Publish latest builds into docker hub
	- Provide capability to run ftw in journal mode
	- Provide capability to run ftw via just py.test

**Comment by csjayp** [comment]
My name is csjp and I 👍 this issue

**Comment by zmallen** [comment]
We need to build a dockerfile in crs-regressions, since it depends on ftw, it doesnt make sense to make a Dockerfile for this project..
