### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by fgsch** [coreruleset/ftw#22]
Full error:

/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/ftw/util.py:86: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

**Comment by fgsch** [comment]
Actually this seems to have been fixed in 364ab9f28db7b2463d0219e778b0905ad1edcb74 but the latest package in pypi is 1.1.6.

Any chance you can release 1.1.7 (I see the tag but not the package)?

**Comment by zmallen** [comment]
https://pypi.org/project/ftw/1.1.7/ 

Can you install/confirm?

**Comment by fgsch** [comment]
Newer travis ci jobs are using 1.1.7 so I will close this.
