### ISSUE TITLE
Latest PyPi package not yet compatible with Python 3

### ISSUE THREAD

**Issue by pirxthepilot** [coreruleset/ftw#38]
Hello, was wondering when you will push a more recent version of ftw to PyPi?

https://pypi.org/project/ftw/

I used the one from there but couldn't get my tests to run under Python 3.6. The latest commit in the master branch works fine, however.

Thanks!

**Comment by airween** [comment]
Hi @pirxthepilot,

I think it's much more interesting that where came from the version 1.2.0 to PyPI - because the latest version number (here on GH) is [1.1.7](https://github.com/CRS-support/ftw/releases).

Could you try to reinstall this version from PyPI?

**Comment by pirxthepilot** [comment]
@airween hmm that is interesting. is there a way to trace where that v1.2.0 came from?

Installed 1.1.7 from PyPi but unfortunately it didn't work - I think it's still on 2.x only. At the same time, I think the dependency versions are also outdated.

After installing 1.1.7:

```
$ py.test -v test.py --ruledir=yaml
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --ruledir=yaml
```
I then upgraded pytest (ignoring the warning):
```
$ pip install -U pytest
...
ERROR: ftw 1.1.7 has requirement pytest==2.9.1, but you'll have pytest 5.3.2 which is incompatible.
...
```
Testing again:
```
$ py.test -v test.py --ruledir=yaml
...
  File "/xxx/miniconda3/envs/ftw/lib/python3.6/site-packages/ftw/__init__.py", line 2, in <module>
ModuleNotFoundError: No module named 'logchecker'
```
Also:
```
$ cat ./miniconda3/envs/ftw/lib/python3.6/site-packages/ftw/__init__.py
import http
import logchecker
import ruleset
import testrunner
import util
import errors
```

**Comment by airween** [comment]
> hmm that is interesting. is there a way to trace where that v1.2.0 came from?

I don't know - checked the tarball, but didn't found any relevant info.

Yes, I also played with the PyPI version of ftw (1.1.7), and got similar results as you. It needs to more investigation, but may be it would be better to make a new release (1.1.8) from the current master.

Note, that if the new release would be 1.1.8 (or any other but less than 1.2.0), then the PyPI wouldn't allow it. The next release must be the 1.2.1 least - as I know you can't upload the lower version from any package, but may be I'm wrong. @fgsch, @fzipi, any ideas?

I think the best solution is that you use the master version while we will solve this.

**Comment by fgsch** [comment]
I just tried installing it from scratch and this works as expected, meaning 1.2.0 is installed from pypi.
Can you try removing it and reinstalling it, ensuring you are using the pip script corresponding to python3?

**Comment by fgsch** [comment]
Actually, for now install from this repo as @airween suggested as 1.2.0 has some issues.
You can do that with `pip3 install  git+https://github.com/CRS-support/ftw`. 
I will try to organise a new release soon. Sorry about that.

**Comment by pirxthepilot** [comment]
No worries, just using latest master for now. Thanks!

**Comment by fzipi** [comment]
A new release is coming in the next weeks, with py3 support, stay tuned.

**Comment by fgsch** [comment]
Sorry for the delay. ftw 1.2.3 has Python 3 support. 
There are still some issues to fix but you can use it instead of master for now.
