### ISSUE TITLE
Overriding Host header (potentially others) at runtime (e.g. with destaddr)

### ISSUE THREAD

**Issue by bobrich** [coreruleset/ftw#46]
Is there some mechanism to pass runtime parameters into the test so that they override values in the yaml files?

In particular we have an issue where we need the Host: header to match the 'destaddr' hostname for most cases (unless we are testing the Host: header itself).  Is there some way to do this with the current FTW capability?  (Either in the general case or this specific one).  Without this we need to do bulk operations against the yaml files to rewrite the Host header.  I've tried without defining the Host header in the yaml, and that doesn't seem to work b/c (as expected) it isn't in the request.

Thanks!

**Comment by fgsch** [comment]
Sorry for the delay.  
I believe you should be able to override the Host header with something like this:

```
def run_tests(ruleset, test, destaddr):
    runner = testrunner.TestRunner()
    for stage in test.stages:
        if destaddr is not None:
            stage.input.dest_addr = destaddr
            stage.input.headers["Host"] = destaddr
        runner.run_stage(stage)
```

Let us know if this doesn't work or I misunderstood your question.
