### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Haalia** [coreruleset/ftw#64]
Hi, is there a way to have FTW use my organization's proxy server?  I'm not finding a way to pass a proxy address into the py.test invocation, and it doesn't pick up the proxy as an environment variable in my shell, which does work with curl.

**Comment by fzipi360** [comment]
FTW uses raw TCP sockets, and values come from the yaml test itself. There is no way to do this, sadly, unless you change your tests to include the calls to your HTTP proxy.

But then, what are you really testing? Aren't you testing also your proxy instead?

I would recommend against going through a proxy.

**Comment by fzipi** [comment]
FTW uses raw TCP sockets, and values come from the yaml test itself. There is no way to do this, sadly, unless you change your tests to include the calls to your HTTP proxy.

But then, what are you really testing? Aren't you testing also your proxy instead?

I would recommend against going through a proxy.
