### ISSUE TITLE
Does this repo work?

### ISSUE THREAD

**Issue by nabheet** [coreruleset/ftw#67]
I followed the instructions and got a bunch of errors. I can post the details if this repo is still supposed to be operational?

**Comment by fzipi** [comment]
We used on a daily basis. What do you mean? :)

If you are having errors, please let us know....

**Comment by nabheet** [comment]
> We used on a daily basis. What do you mean? :)
> 
> If you are having errors, please let us know....

LOL! Sorry for the incomplete message. Please give me a few days and I will get the output for you. Thank you for the reply.

**Comment by fzipi** [comment]
😄 No worries!

**Comment by fzipi** [comment]
@nabheet Were you able to get the output? If yes, please create a new issue with the description of your problem. Closing this one.
